#!/usr/bin/env python3
"""
Deploy a version of the specification to gh-pages branch.

This script:
1. Builds the specification using npm run build
2. Creates a temporary directory with version structure (vX.Y.Z, latest, index.html)
3. Uses ghp-import to deploy to gh-pages branch
4. Optionally pushes to remote

Usage:
    python scripts/deploy-version.py 1.0.0
    python scripts/deploy-version.py 2.0.0 --no-latest
    python scripts/deploy-version.py 3.0.0 --no-push  # Test locally
"""

import sys
import os
import shutil
import subprocess
import argparse
import tempfile
from pathlib import Path
from datetime import datetime


def run_cmd(cmd, cwd=None, check=True, capture=True):
    """Run a shell command and return output."""
    result = subprocess.run(
        cmd if isinstance(cmd, list) else cmd.split(),
        cwd=cwd,
        check=check,
        capture_output=capture,
        text=True,
    )
    return result.stdout.strip() if capture else None


def get_existing_versions():
    """Get list of existing versions from gh-pages branch."""
    try:
        # Check if gh-pages branch exists
        result = run_cmd(["git", "rev-parse", "--verify", "gh-pages"], check=False)
        if not result:
            return []

        # Get list of directories from gh-pages
        result = run_cmd(
            ["git", "ls-tree", "-d", "--name-only", "gh-pages"], check=False
        )
        if not result:
            return []

        versions = []
        for line in result.split("\n"):
            if line.startswith("v") and "." in line:
                versions.append(line)
        return versions
    except Exception as e:
        # If we can't get versions, return empty list (will be first deploy)
        return []


def deploy_version(
    version, make_latest=True, push=True, verbose=False, skip_build=False
):
    """Deploy a version to gh-pages branch using ghp-import."""

    print(f"\n{'=' * 60}")
    print(f"📦 Deploying version {version}")
    print(f"{'=' * 60}\n")

    # Step 1: Build the specification
    if skip_build:
        print("🔨 Step 1: Skipping build (--skip-build)...")
    else:
        print("🔨 Step 1: Building specification...")
        try:
            run_cmd(["npm", "run", "build"], capture=False)
        except subprocess.CalledProcessError as e:
            print(f"❌ Build failed: {e}")
            return False

    built_file = Path("build/index.html")
    if not built_file.exists():
        print(f"❌ Build output not found: {built_file}")
        return False

    file_size_kb = built_file.stat().st_size // 1024
    print(f"✓ Built: {built_file} ({file_size_kb} KB)")

    # Step 2: Get existing versions from gh-pages
    print("\n📥 Step 2: Checking existing versions...")
    existing_versions = get_existing_versions()
    if existing_versions:
        print(
            f"✓ Found {len(existing_versions)} existing versions: {', '.join(existing_versions)}"
        )
    else:
        print("✓ No existing versions (first deploy)")

    # Step 3: Create temporary directory with full site structure
    print(f"\n📋 Step 3: Creating deployment structure...")

    with tempfile.TemporaryDirectory() as tmpdir:
        deploy_dir = Path(tmpdir) / "deploy"
        deploy_dir.mkdir()

        # Copy new version
        version_dir = deploy_dir / f"v{version}"
        version_dir.mkdir(parents=True)
        shutil.copy(built_file, version_dir / "index.html")
        print(f"✓ Created v{version}/index.html")

        # Copy additional assets if they exist
        assets_dir = Path("build/assets")
        if assets_dir.exists():
            shutil.copytree(assets_dir, version_dir / "assets", dirs_exist_ok=True)
            print(f"✓ Copied assets")

        # Step 4: Update 'latest' symlink/copy
        if make_latest:
            print(f"\n🔗 Step 4: Updating 'latest' → v{version}...")
            latest_dir = deploy_dir / "latest"
            shutil.copytree(version_dir, latest_dir)
            print(f"✓ Updated latest → v{version}")
        else:
            print(f"\n⏭️  Step 4: Skipping 'latest' update (--no-latest)")

        # Step 5: Generate version selector index
        print(f"\n📄 Step 5: Generating version selector...")

        # For the index, we need to include the new version plus existing ones
        all_versions = existing_versions + [f"v{version}"]
        # Remove duplicates and sort
        all_versions = sorted(list(set(all_versions)), reverse=True)

        generate_index(deploy_dir, all_versions)
        print(f"✓ Generated index.html with {len(all_versions)} versions")

        # Step 6: Create README
        readme = deploy_dir / "README.md"
        readme.write_text(
            "# Published Specifications\n\n"
            "This branch contains auto-generated documentation.\n"
            "Do not edit manually - all changes will be overwritten.\n\n"
            "Generated by: scripts/deploy-version.py\n"
        )
        print(f"✓ Created README.md")

        # Step 7: Deploy using ghp-import
        print(f"\n📤 Step 6: Deploying with ghp-import...")

        commit_msg = f"Deploy v{version}"
        if make_latest:
            commit_msg += " (latest)"

        ghp_import_cmd = [
            "ghp-import",
            "-n",  # Include .nojekyll file
            "-m",
            commit_msg,  # Commit message
            "-b",
            "gh-pages",  # Target branch
        ]

        if push:
            ghp_import_cmd.append("-p")  # Push to remote

        if verbose:
            ghp_import_cmd.append("-f")  # Force (useful for debugging)

        ghp_import_cmd.append(str(deploy_dir))  # Directory to import

        if verbose:
            print(f"   Running: {' '.join(ghp_import_cmd)}")

        try:
            run_cmd(ghp_import_cmd, capture=not verbose)
            print(f"✓ Deployed to gh-pages branch")
            if push:
                print(f"✓ Pushed to remote")
        except subprocess.CalledProcessError as e:
            print(f"❌ ghp-import failed: {e}")
            if verbose and e.stderr:
                print(f"   stderr: {e.stderr}")
            return False

    # Success!
    print(f"\n{'=' * 60}")
    print(f"✅ Successfully deployed v{version}!")
    print(f"{'=' * 60}")

    if push:
        # Show URL
        try:
            remote_url = run_cmd(["git", "config", "--get", "remote.origin.url"])
            if "github.com" in remote_url:
                # Extract org/repo from URL
                parts = remote_url.replace(".git", "").replace(":", "/").split("/")
                org, repo = parts[-2], parts[-1]

                print(f"\n📍 View at:")
                print(f"   https://{org}.github.io/{repo}/v{version}/")
                if make_latest:
                    print(f"   https://{org}.github.io/{repo}/latest/")
                print(f"   https://{org}.github.io/{repo}/  (version selector)")
        except:
            pass

    return True


def generate_index(deploy_dir, version_list):
    """Generate version selector index.html.

    Args:
        deploy_dir: Directory where index.html will be created
        version_list: List of version directory names (e.g., ['v3.0', 'v2.0', 'v1.0'])
    """

    # Parse version information
    versions = []
    for version_dir in version_list:
        if version_dir.startswith("v"):
            version_num = version_dir[1:]  # Remove 'v' prefix

            # Use current date for new versions, or "Published" for existing
            date_str = datetime.now().strftime("%Y-%m-%d")

            versions.append({"num": version_num, "dir": version_dir, "date": date_str})

    # Sort by version number (newest first)
    def version_sort_key(v):
        # Split on dash to separate version from suffix
        parts = v["num"].split("-")[0].split(".")
        try:
            return [int(x) for x in parts]
        except ValueError:
            # If parsing fails, return a very low value
            return [0]

    versions.sort(key=version_sort_key, reverse=True)

    # Generate HTML
    html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Standard Versions</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 40px 20px;
        }
        
        .container {
            max-width: 800px;
            margin: 0 auto;
        }
        
        h1 {
            font-size: 2.5em;
            color: white;
            margin-bottom: 0.3em;
            text-shadow: 0 2px 4px rgba(0,0,0,0.2);
        }
        
        .subtitle {
            color: rgba(255,255,255,0.9);
            font-size: 1.1em;
            margin-bottom: 2em;
        }
        
        ul {
            list-style: none;
        }
        
        li {
            margin-bottom: 1em;
        }
        
        a {
            display: block;
            padding: 20px 25px;
            background: white;
            text-decoration: none;
            color: #2c3e50;
            border-radius: 8px;
            border: 2px solid transparent;
            transition: all 0.3s ease;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        
        a:hover {
            border-color: #667eea;
            box-shadow: 0 6px 20px rgba(0,0,0,0.15);
            transform: translateY(-2px);
        }
        
        .version-title {
            font-size: 1.3em;
            font-weight: 600;
            color: #2c3e50;
            margin-bottom: 0.3em;
        }
        
        .version-date {
            font-size: 0.9em;
            color: #95a5a6;
        }
        
        .latest {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            border: none;
            box-shadow: 0 6px 20px rgba(102, 126, 234, 0.4);
        }
        
        .latest .version-title,
        .latest .version-date {
            color: white;
        }
        
        .latest:hover {
            box-shadow: 0 8px 25px rgba(102, 126, 234, 0.6);
        }
        
        footer {
            margin-top: 3em;
            padding-top: 2em;
            text-align: center;
            color: rgba(255,255,255,0.8);
            font-size: 0.9em;
        }
        
        footer a {
            display: inline;
            padding: 0;
            background: none;
            color: white;
            border: none;
            box-shadow: none;
            text-decoration: underline;
        }
        
        footer a:hover {
            transform: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>📘 Standard Versions</h1>
        <p class="subtitle">Select a version to view the specification</p>
        
        <ul>
            <li>
                <a href="./latest/" class="latest">
                    <div class="version-title">Latest Version</div>
                    <div class="version-date">Always up-to-date</div>
                </a>
            </li>
"""

    for v in versions:
        html += f"""            <li>
                <a href="./{v["dir"]}/">
                    <div class="version-title">Version {v["num"]}</div>
                    <div class="version-date">Published {v["date"]}</div>
                </a>
            </li>
"""

    html += """        </ul>
        
        <footer>
            Generated automatically by 
            <a href="https://github.com/tamtamresearch/a-standard-repo">a-standard-repo</a>
        </footer>
    </div>
</body>
</html>
"""

    index_file = deploy_dir / "index.html"
    index_file.write_text(html, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(
        description="Deploy specification version to gh-pages",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Deploy version 1.0.0 and update latest
  python scripts/deploy-version.py 1.0.0
  
  # Deploy version 2.0.0 without updating latest
  python scripts/deploy-version.py 2.0.0 --no-latest
  
  # Deploy without pushing (for testing)
  python scripts/deploy-version.py 1.0.0 --no-push
        """,
    )

    parser.add_argument("version", help="Version to deploy (e.g., 1.0.0, 1.1.0, 2.0.0)")

    parser.add_argument(
        "--no-latest",
        dest="make_latest",
        action="store_false",
        default=True,
        help="Don't update 'latest' to point to this version",
    )

    parser.add_argument(
        "--no-push",
        dest="push",
        action="store_false",
        default=True,
        help="Don't push to remote (for testing)",
    )

    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")

    parser.add_argument(
        "--skip-build",
        action="store_true",
        help="Skip build step (use existing build/index.html)",
    )

    args = parser.parse_args()

    # Validate version format (basic check)
    version_parts = args.version.split(".")
    if len(version_parts) < 2 or not all(
        p.replace("-", "").replace("draft", "").replace("rc", "").isdigit()
        or p.isalpha()
        for part in version_parts
        for p in [part.split("-")[0]]
    ):
        print(f"❌ Invalid version format: {args.version}")
        print("   Expected: X.Y.Z (e.g., 1.0.0, 1.1.0, 2.0.0)")
        print("   Or with suffix: X.Y.Z-draft.N, X.Y.Z-rc.N")
        sys.exit(1)

    success = deploy_version(
        args.version,
        make_latest=args.make_latest,
        push=args.push,
        verbose=args.verbose,
        skip_build=args.skip_build,
    )

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
